name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: "\<*_&"
category-template: "### $TITLE"
version-resolver:
  major:
    labels:
      - "SemVer/MAJOR"
      - "kind/breaking-change"
  minor:
    labels:
      - "SemVer/MINOR"
      - "kind/feat"
  patch:
    labels:
      - "SemVer/PATCH"
  default: patch

# Exclude labels from the changelog.
excludeLabels:
  - "ci/skip-changelog"

autolabeler:
  - label: "kind/breaking-change"
    body: "/.*BREAKING CHANGE.*/"
  - label: "ci/skip-changelog"
    body: "/docs: release.+/"
  - label: "kind/feat"
    title: "/^feat: .*/"
  - label: "kind/fix"
    title: "/^fix: .*/"
  - label: "kind/perf"
    title: "/^perf: .*/"
  - label: "kind/refactor"
    title: "/^refactor: .*/"
  - label: "kind/test"
    title: "/^test: .*/"
  - label: "kind/docs"
    title: "/^docs: .*/"
  - label: "kind/style"
    title: "/^style: .*/"
  - label: "kind/build"
    title: "/^build: .*/"
  - label: "kind/ci"
    title: "/^ci: .*/"

categories:
  - title: "ðŸ”¥ Breaking Changes"
    labels:
      - "kind/breaking-change"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "kind/fix"
  - title: "ðŸš€ New Features"
    labels:
      - "kind/feat"
  - title: "ðŸ§ª Tests"
    labels:
      - "kind/test"
  - title: "ðŸ“ Documentation"
    labels:
      - "kind/docs"
  - title: "âœ¨ Improvements"
    labels:
      - "kind/perf"
      - "kind/refactor"
  - title: "ðŸ“¦ Dependencies"
    labels:
      - "kind/build"
  - title: "ðŸƒ Maintenance"
    labels:
      - "kind/style"
      - "kind/ci"

template: |
  ## v$RESOLVED_VERSION - ${{date 'YYYY-MM-DD'}}
  
  [ç®€ä½“ä¸­æ–‡](https://github.com/ZhuoZhuoCrayon/throttled-py/blob/main/CHANGELOG.md#vxxx---${{date 'YYYY-MM-DD'}}) | English

  $CHANGES

  **Full Changelog**: https://github.com/ZhuoZhuoCrayon/throttled-py/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ---
